#[general]
#import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 12

[font.normal]
family = "Terminus"

[cursor.style]
shape = "Block"
blinking = "On"

[colors.primary]
background = "#1f1f1f"

[window]
opacity = 0.90
padding = { x = 55, y = 55 }

[terminal.shell]
program = "/bin/bash"
args = ["-l"]
